/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORT_H_RPCGEN
#define _AIRPORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255
#define CODELEN 3

typedef char *name_as;

typedef char *code_as;

typedef struct coordinates_as location_as;

typedef struct airport_info_as *airport_list_as;

struct airport_info_as {
	code_as airport_code;
	name_as city;
	code_as state;
	double distance;
	airport_list_as next;
};
typedef struct airport_info_as airport_info_as;

struct coordinates_as {
	double latitude;
	double longitude;
};
typedef struct coordinates_as coordinates_as;

struct list_location_res {
	int errno;
	union {
		airport_list_as list_location_res;
	} list_location_res_u;
};
typedef struct list_location_res list_location_res;

#define LOCATIONPROG 0x20001226
#define LOCATIONVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define LISTLOCATION 1
extern  list_location_res * listlocation_1(location_as *, CLIENT *);
extern  list_location_res * listlocation_1_svc(location_as *, struct svc_req *);
extern int locationprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LISTLOCATION 1
extern  list_location_res * listlocation_1();
extern  list_location_res * listlocation_1_svc();
extern int locationprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_name_as (XDR *, name_as*);
extern  bool_t xdr_code_as (XDR *, code_as*);
extern  bool_t xdr_location_as (XDR *, location_as*);
extern  bool_t xdr_airport_list_as (XDR *, airport_list_as*);
extern  bool_t xdr_airport_info_as (XDR *, airport_info_as*);
extern  bool_t xdr_coordinates_as (XDR *, coordinates_as*);
extern  bool_t xdr_list_location_res (XDR *, list_location_res*);

#else /* K&R C */
extern bool_t xdr_name_as ();
extern bool_t xdr_code_as ();
extern bool_t xdr_location_as ();
extern bool_t xdr_airport_list_as ();
extern bool_t xdr_airport_info_as ();
extern bool_t xdr_coordinates_as ();
extern bool_t xdr_list_location_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORT_H_RPCGEN */
