/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255
#define CODELEN 3

typedef char *name;

typedef char *code;

typedef struct final_result final_result_u;

typedef struct coordinates location;

typedef struct airport_info *airport_list;

struct airport_info {
	code airport_code;
	name city;
	code state;
	double distance;
	airport_list next;
};
typedef struct airport_info airport_info;

struct coordinates {
	double latitude;
	double longitude;
};
typedef struct coordinates coordinates;

struct user_input {
	name city;
	code state;
	location loc;
};
typedef struct user_input user_input;

struct final_result {
	struct user_input input_res;
	airport_list list;
};
typedef struct final_result final_result;

struct list_airport {
	int errno;
	union {
		final_result_u result;
	} list_airport_u;
};
typedef struct list_airport list_airport;

#define AIRPORTPROG 0x20000111
#define AIRPORTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LISTAIRPORT 1
extern  list_airport_res * listairport_1(name *, CLIENT *);
extern  list_airport_res * listairport_1_svc(name *, struct svc_req *);
extern int airportprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LISTAIRPORT 1
extern  list_airport_res * listairport_1();
extern  list_airport_res * listairport_1_svc();
extern int airportprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_name (XDR *, name*);
extern  bool_t xdr_code (XDR *, code*);
extern  bool_t xdr_final_result_u (XDR *, final_result_u*);
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_airport_list (XDR *, airport_list*);
extern  bool_t xdr_airport_info (XDR *, airport_info*);
extern  bool_t xdr_coordinates (XDR *, coordinates*);
extern  bool_t xdr_user_input (XDR *, user_input*);
extern  bool_t xdr_final_result (XDR *, final_result*);
extern  bool_t xdr_list_airport (XDR *, list_airport*);

#else /* K&R C */
extern bool_t xdr_name ();
extern bool_t xdr_code ();
extern bool_t xdr_final_result_u ();
extern bool_t xdr_location ();
extern bool_t xdr_airport_list ();
extern bool_t xdr_airport_info ();
extern bool_t xdr_coordinates ();
extern bool_t xdr_user_input ();
extern bool_t xdr_final_result ();
extern bool_t xdr_list_airport ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
