/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"

list_airport_res *
listairport_1_svc(name *argp, struct svc_req *rqstp)
{
	static list_airport_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}
